// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogSend.proto

#include "LogSend.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ik {
PROTOBUF_CONSTEXPR LogSendRequest::LogSendRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.node_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.time_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LogSendRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogSendRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogSendRequestDefaultTypeInternal() {}
  union {
    LogSendRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogSendRequestDefaultTypeInternal _LogSendRequest_default_instance_;
PROTOBUF_CONSTEXPR LogSendReponse::LogSendReponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.msg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.serial_)*/0
  , /*decltype(_impl_.is_end_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LogSendReponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogSendReponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogSendReponseDefaultTypeInternal() {}
  union {
    LogSendReponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogSendReponseDefaultTypeInternal _LogSendReponse_default_instance_;
}  // namespace ik
static ::_pb::Metadata file_level_metadata_LogSend_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_LogSend_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_LogSend_2eproto = nullptr;

const uint32_t TableStruct_LogSend_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ik::LogSendRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ik::LogSendRequest, _impl_.node_name_),
  PROTOBUF_FIELD_OFFSET(::ik::LogSendRequest, _impl_.time_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ik::LogSendReponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ik::LogSendReponse, _impl_.serial_),
  PROTOBUF_FIELD_OFFSET(::ik::LogSendReponse, _impl_.is_end_),
  PROTOBUF_FIELD_OFFSET(::ik::LogSendReponse, _impl_.msg_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ik::LogSendRequest)},
  { 8, -1, -1, sizeof(::ik::LogSendReponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ik::_LogSendRequest_default_instance_._instance,
  &::ik::_LogSendReponse_default_instance_._instance,
};

const char descriptor_table_protodef_LogSend_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rLogSend.proto\022\002ik\"1\n\016LogSendRequest\022\021\n"
  "\tnode_name\030\001 \001(\014\022\014\n\004time\030\002 \001(\014\"=\n\016LogSen"
  "dReponse\022\016\n\006serial\030\001 \001(\005\022\016\n\006is_end\030\002 \001(\010"
  "\022\013\n\003msg\030\003 \001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_LogSend_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_LogSend_2eproto = {
    false, false, 141, descriptor_table_protodef_LogSend_2eproto,
    "LogSend.proto",
    &descriptor_table_LogSend_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_LogSend_2eproto::offsets,
    file_level_metadata_LogSend_2eproto, file_level_enum_descriptors_LogSend_2eproto,
    file_level_service_descriptors_LogSend_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_LogSend_2eproto_getter() {
  return &descriptor_table_LogSend_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_LogSend_2eproto(&descriptor_table_LogSend_2eproto);
namespace ik {

// ===================================================================

class LogSendRequest::_Internal {
 public:
};

LogSendRequest::LogSendRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ik.LogSendRequest)
}
LogSendRequest::LogSendRequest(const LogSendRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LogSendRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.node_name_){}
    , decltype(_impl_.time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.node_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_node_name().empty()) {
    _this->_impl_.node_name_.Set(from._internal_node_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.time_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_time().empty()) {
    _this->_impl_.time_.Set(from._internal_time(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ik.LogSendRequest)
}

inline void LogSendRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.node_name_){}
    , decltype(_impl_.time_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.node_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.time_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LogSendRequest::~LogSendRequest() {
  // @@protoc_insertion_point(destructor:ik.LogSendRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LogSendRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.node_name_.Destroy();
  _impl_.time_.Destroy();
}

void LogSendRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LogSendRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ik.LogSendRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.node_name_.ClearToEmpty();
  _impl_.time_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogSendRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes node_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_node_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_time();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LogSendRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ik.LogSendRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes node_name = 1;
  if (!this->_internal_node_name().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_node_name(), target);
  }

  // bytes time = 2;
  if (!this->_internal_time().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ik.LogSendRequest)
  return target;
}

size_t LogSendRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ik.LogSendRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes node_name = 1;
  if (!this->_internal_node_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_node_name());
  }

  // bytes time = 2;
  if (!this->_internal_time().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LogSendRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LogSendRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LogSendRequest::GetClassData() const { return &_class_data_; }


void LogSendRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LogSendRequest*>(&to_msg);
  auto& from = static_cast<const LogSendRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ik.LogSendRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_node_name().empty()) {
    _this->_internal_set_node_name(from._internal_node_name());
  }
  if (!from._internal_time().empty()) {
    _this->_internal_set_time(from._internal_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LogSendRequest::CopyFrom(const LogSendRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ik.LogSendRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogSendRequest::IsInitialized() const {
  return true;
}

void LogSendRequest::InternalSwap(LogSendRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.node_name_, lhs_arena,
      &other->_impl_.node_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.time_, lhs_arena,
      &other->_impl_.time_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata LogSendRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LogSend_2eproto_getter, &descriptor_table_LogSend_2eproto_once,
      file_level_metadata_LogSend_2eproto[0]);
}

// ===================================================================

class LogSendReponse::_Internal {
 public:
};

LogSendReponse::LogSendReponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ik.LogSendReponse)
}
LogSendReponse::LogSendReponse(const LogSendReponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LogSendReponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_){}
    , decltype(_impl_.serial_){}
    , decltype(_impl_.is_end_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_msg().empty()) {
    _this->_impl_.msg_.Set(from._internal_msg(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.serial_, &from._impl_.serial_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_end_) -
    reinterpret_cast<char*>(&_impl_.serial_)) + sizeof(_impl_.is_end_));
  // @@protoc_insertion_point(copy_constructor:ik.LogSendReponse)
}

inline void LogSendReponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_){}
    , decltype(_impl_.serial_){0}
    , decltype(_impl_.is_end_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LogSendReponse::~LogSendReponse() {
  // @@protoc_insertion_point(destructor:ik.LogSendReponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LogSendReponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.msg_.Destroy();
}

void LogSendReponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LogSendReponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ik.LogSendReponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  ::memset(&_impl_.serial_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_end_) -
      reinterpret_cast<char*>(&_impl_.serial_)) + sizeof(_impl_.is_end_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogSendReponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 serial = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.serial_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_end = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.is_end_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes msg = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_msg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LogSendReponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ik.LogSendReponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 serial = 1;
  if (this->_internal_serial() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_serial(), target);
  }

  // bool is_end = 2;
  if (this->_internal_is_end() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_is_end(), target);
  }

  // bytes msg = 3;
  if (!this->_internal_msg().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_msg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ik.LogSendReponse)
  return target;
}

size_t LogSendReponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ik.LogSendReponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes msg = 3;
  if (!this->_internal_msg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_msg());
  }

  // int32 serial = 1;
  if (this->_internal_serial() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_serial());
  }

  // bool is_end = 2;
  if (this->_internal_is_end() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LogSendReponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LogSendReponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LogSendReponse::GetClassData() const { return &_class_data_; }


void LogSendReponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LogSendReponse*>(&to_msg);
  auto& from = static_cast<const LogSendReponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ik.LogSendReponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_serial() != 0) {
    _this->_internal_set_serial(from._internal_serial());
  }
  if (from._internal_is_end() != 0) {
    _this->_internal_set_is_end(from._internal_is_end());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LogSendReponse::CopyFrom(const LogSendReponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ik.LogSendReponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogSendReponse::IsInitialized() const {
  return true;
}

void LogSendReponse::InternalSwap(LogSendReponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.msg_, lhs_arena,
      &other->_impl_.msg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LogSendReponse, _impl_.is_end_)
      + sizeof(LogSendReponse::_impl_.is_end_)
      - PROTOBUF_FIELD_OFFSET(LogSendReponse, _impl_.serial_)>(
          reinterpret_cast<char*>(&_impl_.serial_),
          reinterpret_cast<char*>(&other->_impl_.serial_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LogSendReponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LogSend_2eproto_getter, &descriptor_table_LogSend_2eproto_once,
      file_level_metadata_LogSend_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ik
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ik::LogSendRequest*
Arena::CreateMaybeMessage< ::ik::LogSendRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ik::LogSendRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ik::LogSendReponse*
Arena::CreateMaybeMessage< ::ik::LogSendReponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ik::LogSendReponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
